apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-container-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-container-app
    app.kubernetes.io/part-of: single-container-app
  name: single-container-app
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: single-container-app
status:
  loadBalancer: {}
