apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: single-container-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: single-container-app
    app.kubernetes.io/part-of: single-container-app
  name: single-container-apppiun
spec:
  path: /
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: single-container-app
    weight: null
status: {}
